import PageMeta from '@/components/common/PageMeta';
import Breadcrumb from '@/components/common/Breadcrumb';

export default function TermsPage() {
  return (
    <>
      <PageMeta
        title="Terms of Use - CalcWise AI"
        description="Read the Terms of Use for CalcWise AI. All calculator results are for informational purposes only and do not constitute financial, health, or legal advice."
        canonical="https://www.calculatorpilotai.com/terms"
      />
      <div className="min-h-screen bg-slate-50">
        <main className="max-w-3xl mx-auto px-4 py-8 md:py-20">
          <Breadcrumb items={[
            { name: 'Home', url: '/' },
            { name: 'Terms of Use' },
          ]} />
          <p className="text-xs font-bold uppercase tracking-widest text-primary mb-3">Legal</p>
          <h1 className="text-3xl md:text-4xl font-black text-slate-900 mb-4 tracking-tight">
            Terms of Use
          </h1>
          <p className="text-slate-500 text-sm mb-10">Effective date: January 1, 2026 &nbsp;·&nbsp; Last updated: May 24, 2026</p>

          <div className="space-y-8 text-slate-700 leading-relaxed">
            <section>
              <p className="text-base text-slate-600">
                Welcome to CalcWise AI. By accessing or using this website and any tools, calculators, or content available on it, you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use this Site.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3 uppercase tracking-widest text-sm">1. Acceptance of Terms</h2>
              <p>
                These Terms of Use govern your access to and use of <strong>www.calculatorpilotai.com</strong> (the "Site"), operated by CalcWise AI ("we", "us", or "our"). By using the Site, you represent that you are at least 13 years of age and have the legal capacity to agree to these terms.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3 uppercase tracking-widest text-sm">2. Informational Purpose Only — Important Disclaimer</h2>
              <div className="bg-amber-50 border border-amber-200 rounded-lg p-5 mt-3">
                <p className="font-bold text-amber-900 mb-2">⚠ All calculation results are for informational and educational purposes only.</p>
                <p className="text-amber-800 text-sm leading-relaxed">
                  The calculators, tools, AI insights, guides, and comparison content available on this Site do not constitute and should not be relied upon as professional financial, investment, tax, legal, medical, health, or logistical advice. Results generated by our tools are estimates based on the inputs you provide and the algorithms we have implemented — they may not reflect your complete financial situation, health status, or specific legal circumstances.
                </p>
              </div>
              <p className="mt-4">
                Specifically:
              </p>
              <ul className="list-disc list-inside mt-3 space-y-2 text-slate-600">
                <li><strong>Mortgage Calculator:</strong> Results are estimates only. Actual mortgage terms, rates, and payments are determined by your lender and depend on factors not captured by this tool, including your credit score, property taxes, insurance, and lender-specific fees. Always consult a licensed mortgage professional or financial advisor before making home financing decisions.</li>
                <li><strong>BMI & Calorie Calculator:</strong> BMI is a screening tool, not a diagnostic measure. It does not account for muscle mass, bone density, age, sex, or other individual factors. Calorie estimates are approximations. Consult a licensed healthcare provider or registered dietitian before making changes to your diet or exercise routine.</li>
                <li><strong>Shipping Calculator:</strong> Dimensional weight calculations are estimates based on standard carrier formulas. Actual shipping charges may vary based on carrier surcharges, zone pricing, fuel adjustments, and package characteristics. Always verify costs directly with your carrier.</li>
                <li><strong>AI Text Detector:</strong> The detection result is a probabilistic estimate based on heuristic analysis. It is not definitive proof of AI or human authorship and should not be used as the sole basis for academic, legal, or employment decisions.</li>
              </ul>
              <p className="mt-4">
                We strongly encourage you to consult with qualified professionals — including financial advisors, physicians, attorneys, and logistics specialists — before making any significant decisions based on information obtained from this Site.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3 uppercase tracking-widest text-sm">3. No Warranties</h2>
              <p>
                The Site and all its content, tools, and calculators are provided on an "as is" and "as available" basis without any warranties of any kind, either express or implied. We do not warrant that the Site will be uninterrupted, error-free, or free of viruses or other harmful components. We make no warranty regarding the accuracy, completeness, reliability, or suitability of any information or calculation result.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3 uppercase tracking-widest text-sm">4. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by applicable law, CalcWise AI shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, the Site or its content. This includes but is not limited to any financial losses, health outcomes, or logistical decisions made based on calculations or insights generated by our tools.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3 uppercase tracking-widest text-sm">5. Intellectual Property</h2>
              <p>
                All content on this Site, including text, graphics, logos, icons, and software, is the property of CalcWise AI or its content suppliers and is protected by applicable intellectual property laws. You may not reproduce, distribute, modify, or create derivative works of any content without our prior written permission.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3 uppercase tracking-widest text-sm">6. Permitted Use</h2>
              <p>You may use the Site for lawful, personal, and non-commercial purposes. You agree not to:</p>
              <ul className="list-disc list-inside mt-3 space-y-2 text-slate-600">
                <li>Attempt to gain unauthorized access to any part of the Site</li>
                <li>Use automated tools to scrape or harvest data from the Site at scale</li>
                <li>Introduce malicious code or interfere with the Site's operation</li>
                <li>Use the Site in any way that violates applicable local, national, or international laws</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3 uppercase tracking-widest text-sm">7. Third-Party Links</h2>
              <p>
                The Site may contain links to third-party websites for reference or convenience. We have no control over the content, privacy practices, or availability of those sites and are not responsible for any damages or losses arising from your use of them.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3 uppercase tracking-widest text-sm">8. Modifications to Terms</h2>
              <p>
                We reserve the right to update these Terms of Use at any time. Changes will be effective upon posting to the Site. Your continued use of the Site after changes are posted constitutes your acceptance of the updated terms.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3 uppercase tracking-widest text-sm">9. Governing Law</h2>
              <p>
                These Terms are governed by the laws of the United States. Any disputes arising from these Terms or your use of the Site shall be subject to the exclusive jurisdiction of the courts located in the United States.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900 mb-3 uppercase tracking-widest text-sm">10. Contact</h2>
              <p>
                For questions regarding these Terms of Use, contact us at <a href="mailto:support@calculatorpilotai.com" className="text-primary font-semibold hover:underline">support@calculatorpilotai.com</a>.
              </p>
            </section>
          </div>
        </main>
      </div>
    </>
  );
}
